name: Node.js CI # Tên của workflow (tùy ý)
on: [push] # Kích hoạt khi có sự kiện push (mọi nhánh)
jobs:
  build:
    runs-on: ubuntu-latest # Chạy trên máy ảo Ubuntu do GitHub cung cấp
    steps:
      - uses: actions/checkout@v5 # Bước 1: Checkout code từ repo
      - uses: actions/setup-node@v4 # Bước 2: Cài Node.js
        with:
          node-version: "20.x" #      Sử dụng Node.js phiên bản 20.x
      - name: Install dependencies
        run: npm install # Bước 3: Cài các package (npm ci cũng được)
      - name: Run tests
        run: npm test # Bước 4: Chạy bộ test (Jest)
